inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/**'
    - 'config/**/**'
    - 'node_modules/**/**'
    - 'log/**/**'
    - 'tmp/**/**'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/**'
