require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'app/channels/**/**'
    - 'app/mailers/**'
    - 'bin/**/**'
    - 'db/**/**'
    - 'config/**/**'
    - 'node_modules/**/**'
    - 'log/**/**'
    - 'tmp/**/**'
    - 'Rakefile'
    - 'config.ru'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/**'
